# api-gateway/nginx.conf
events {}

http {
    server {
        listen 80;

        location /notes/ {
            proxy_pass http://request-service:8000/;
        }

        location /groups/ {
            proxy_pass http://group-service:8001/;
        }
    }
}